config/routes.rb
Rails.application.routes.draw do



  ########################################################################################################
  
  namespace :admin do
    
    controller :users do
    end
    resources :users
    
    controller :categorias do
    end
    resources :categorias
    
    controller :produtos do
    end
    resources :produtos
    
    controller :pages do
      get '/home' => :home
      get '/logs' => :logs
    end

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}
    
    controller :produtos do
    end
    resources :produtos, only: [:show, :index]

  controller :pages do
    get '/home' => :home
  end

  root 'pages#home'
  get '*path' => redirect('/')
end

app/views/admin/pages/logs.html.erb
<div class="row">
	<div class="col s12 m12 l12">
		<table>
			<thead>
				<tr>
					<th></th>
					<th>Evento</th>
					<th>Descrição</th>
					<th>Data</th>
					<th>Ações</th>
				</tr>
			</thead>

			<tbody>
			<% @logs.each do |log| %>
				<tr>
					<td><%= "<span class='new badge green'>&nbsp;</span>".html_safe if new_log(log) %></td>
					<td class="<%= log_class log %>-text"><%= log.descricao %></td>
					<td><%= descricao_log(log) %></td>
					<td><%= l log.created_at, format: :long %></td>
					<td class="actions">
						<% unless log_class(log) == "red" %>
							<a href="<%= log_url(log) %>" class="btn shadow blue small">
								<i class='material-icons'>search</i>
							</a>
						<% end %>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>		
	</div>
</div>