config/routes.rb
Rails.application.routes.draw do



  ########################################################################################################
  
  namespace :admin do
    
    controller :users do
    end
    resources :users
    
    controller :categorias do
    end
    resources :categorias
    
    controller :produtos do
    end
    resources :produtos
    
    controller :pages do
      get '/home' => :home
      get '/logs' => :logs
    end

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}
    
    controller :produtos do
    end
    resources :produtos, only: [:show, :index]

  controller :pages do
    get '/home' => :home
  end

  root 'pages#home'
  get '*path' => redirect('/')
end

app/models/produto.rb
class Produto < ApplicationRecord
  usar_como_dinheiro :preco, :preco_final, :custo

  validates :nome, :categoria, presence: true
  validates :nome, uniqueness: { scope: :categoria }

  belongs_to :categoria
  
  mount_uploaders :fotos, ImagemUploader

  after_create :log_for_create
  #after_update :log_for_update, if: -> { self.changes }

  def log_for_create
    Log.create(descricao: "Novo produto criada!", objeto: {"class" => "green", "id" => self.id, "tipo" => "produtos", "descricao" => "#{self.nome} - #{self.descricao}"})
  end

  def log_for_update
    Log.create(descricao: "Alteração na produto #{self.id} - #{self.nome}", objeto: {"id" => self.id, "tipo" => "user", "descricao" => "#{self.nome} - #{self.descricao}"}) 
  end

end

app/controllers/admin/produtos_controller.rb
class Admin::ProdutosController < Admin::ApplicationController
    before_action :set_produto, only: [:show, :edit, :update, :destroy]
      skip_before_action :verify_authenticity_token

    def index
        conditions = []
        conditions << "produtos.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
        conditions << "produtos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
        @produtos = Produto.where(conditions.join(" AND ")).order("created_at desc")
    end

    def show
    end

    def edit
    end

    def update
      if @produto.update(produto_params)
        if params[:produto][:imagem_capa].blank?
          respond_to do |format|
            format.js {render inline: "M.toast({html: 'Atualizado!', classes: 'green'}); " }
          end
        else
          redirect_to request.referrer, notice: "Atualizado"
        end
      else
        respond_to do |format|
          format.js
        end
      end
    end

    def new
    	@produto = Produto.new
    end

    def create
    	@produto = Produto.new(produto_params)
    	if @produto.save
            redirect_to edit_admin_produto_path(@produto), notice: "Produto #{@produto.nome} criado com sucesso!"
        else
            respond_to do |format|
                format.js
            end
        end
    end

    def destroy
      if @produto.modulos.size > 0
        Log.create(descricao: "Tentativa de deletar Produto!", objeto: {"id" => @produto.id, "tipo" => "produtos", "descricao" => "#{@produto.nome} - Tentativa de (#{current_user.id}) #{nome}", "class" => "orange", "user_id" => "#{current_user.id}"})
        respond_to do |format|
          format.js {render inline: "M.toast({html: 'Não foi possível deletar o produto #{@produto.nome}, módulos existentes.', classes: 'red'}); " }
        end
      else
        l = Log.new(descricao: "Produto deletado!", objeto: {"id" => @produto.id, "tipo" => "produtos", "descricao" => "#{@produto.nome} deletada por (#{current_user.id}) #{nome}", "class" => "red", "user_id" => "#{current_user.id}"})
        if @produto.destroy
          l.save
        else
          respond_to do |format|
            Log.create(descricao: "Tentativa de deletar Produto!", objeto: {"id" => @produto.id, "tipo" => "produtos", "descricao" => "#{@produto.nome} - Tentativa de (#{current_user.id}) #{nome}", "class" => "orange", "user_id" => "#{current_user.id}"})
            format.js {render inline: "M.toast({html: 'Não foi possível deletar o produto #{@produto.nome}, módulos existentes.', classes: 'red'}); " }
          end
        end 
      end
  end

  private

  def produto_params
      params.require(:produto).permit(:nome, :descricao, :preco, :desconto, :preco_final, :custo, 
                                      :ativo, :destaque, :categoria_id, {fotos: []})
  end

  def set_produto
   @produto = Produto.find(params[:id])
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
    
    def index
        conditions = []
        unless params[:search].blank?
        	conditions << "((produtos.nome LIKE '%#{params[:search]}%') OR 
        									(produtos.descricao LIKE '%#{params[:search]}%') OR
        									(categorias.nome LIKE '%#{params[:search]}%') OR
        									(categorias.descricao LIKE '%#{params[:search]}%'))" 
      	end
      	conditions << "produtos.categoria_id = #{params[:categoria]}" unless params[:categoria].blank?
        @produtos = Produto.joins(:categoria).where(conditions.join(" AND ")).order("created_at desc")
    end

    def show
    	@produto = Produto.find(params[:id])
    end

end

app/helpers/produto_helper.rb
module ProdutoHelper

	def capa produto
		if produto.fotos.first.blank?
			if produto.categoria.oculos?
				return "/images/produtos/oculos/#{rand(1..10)}.jpg"
			elsif produto.categoria.relogios?
				return "/images/produtos/relogios/#{rand(1..10)}.jpg"
			elsif produto.categoria.tenis?
				return "/images/produtos/tenis/#{rand(1..10)}.jpg"
			end
		else
			return produto.fotos.fill_medium
		end
	end

	def relogios limite = 3
		Produto.where(categoria_id: Categoria.relogios.ids).limit(limite)
	end

	def tenis limite = 3
		Produto.where(categoria_id: Categoria.tenis.ids).limit(limite)
	end

	def oculos limite = 3
		Produto.where(categoria_id: Categoria.oculos.ids).limit(limite)
	end

	def relogios? produto
		produto.categoria.relogios?
	end

	def tenis? produto
		produto.categoria.tenis?
	end

	def oculos? produto
		produto.categoria.oculos?
	end


end

app/views/admin/produtos/_form.html.erb
	<%= form_for [:admin, @produto], remote: true do |f| %>
		<div class="row">
			<div class="col s12 m12 l12">
			<br>
				<div class="card">
					<div class="card-content">
						<div class="row">
							<div class="field">
								<div class="input-field col s12 m12 l12">
									<i class="material-icons prefix">description</i>
									<%= f.text_field :nome  %>
									<label for="produto_nome">Name</label>
								</div>
							</div>

							<div class="field">
								<div class="input-field col s12 m12 l12">
									<i class="material-icons prefix">description</i>
									<%= f.text_field :descricao %>
									<label for="produto_descricao">Descrição</label>
								</div>
							</div>

							<div class="field">
								<div class="input-field col s12 m12 l12">
									<i class="material-icons prefix">local_offer</i>
									<%= f.collection_select :categoria_id, Categoria.all.order("categorias.nome ASC"), :id, :nome, { prompt: "Selecionar Categoria" } %>
									<%= f.label :categoria %>
								</div>
							</div>

						</div>
						<div class="row">
							<div class="field">
								<div class="input-field col s12 m12 l6">
									<i class="material-icons prefix">monetization_on</i>
									<%= f.text_field :custo, :onkeypress => "mascara(this, checaValor)", maxlength: 9   %>
									<label for="produto_custo">Custo</label>
								</div>
							</div>
							<div class="field">
								<div class="input-field col s12 m12 l6">
									<i class="material-icons prefix">monetization_on</i>
									<%= f.text_field :preco, class: "calcular", :onkeypress => "mascara(this, checaValor)", maxlength: 9   %>
									<label for="produto_preco">Preço</label>
								</div>
							</div>
							<div class="field">
								<div class="input-field col s12 m12 l6">
									<i class="material-icons prefix">monetization_on</i>
									<%= f.text_field :desconto, class: "calcular", :onkeypress => "mascara(this, checaNumero)"  %>
									<label for="produto_desconto">Desconto (%)</label>
								</div>
							</div>
							<div class="field">
								<div class="input-field col s12 m12 l6">
									<i class="material-icons prefix">monetization_on</i>
									<%= f.text_field :preco_final, :onkeypress => "mascara(this, checaValor)", maxlength: 9 %>
									<label for="produto_total">Total</label>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col s12 m12 l3" >
								<label>
									<%= f.check_box :ativo, class: "filled-in checkbox"  %> 
									<span class="">Ativo</span>
								</label>
							</div>
							<div class="col s12 m12 l3" >
								<label>
									<%= f.check_box :destaque, class: "filled-in checkbox"  %> 
									<span class="">Destaque</span>
								</label>
							</div>
						</div>
						<div class="row">
							<div class="col s12 m12 l12">
								<div class="file-field input-field">
									<div class="btn blue">
									    <span>FOTOS</span>
										<%= f.file_field :fotos, multiple: true %>
									</div>
									<div class="file-path-wrapper">
										<input class=" validate" type="text" placeholder="Adiconar imagem ">
									</div>
								</div>
							</div>
							<div class="col s12 m12 l12">
								<div class="row">
									<% unless @produto.fotos.blank? %>
										<% @produto.fotos.each do |foto| %>
												<div class="col s6 m3 l2">
													<img src="<%= foto %>" class="" style="height: 100px; width: auto;">
												</div>
										<% end %>
									<% end %>
								</div>
							</div>
						</div>
						<div class="action  ">
							<button type="submit" class="send btn shadow green dark small right">Salvar</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>


<script type="text/javascript">
	$(".calcular").keyup(function(){
		var preco = parseFloat($("#produto_preco").prop('value').replace(".", "").replace(",", ".")).toFixed(2);
		var desconto = parseFloat($("#produto_desconto").prop('value'));
		desconto = desconto || 0
		desconto = parseFloat((preco*desconto/100)).toFixed(2);
		console.log("preco: "+preco)
		console.log("desconto: "+desconto)
		preco_final = parseFloat(""+(preco-desconto)).toFixed(2);
		$("#produto_preco_final").val(preco_final);
		console.log("preco_final: "+preco_final)
		M.updateTextFields();
	});
</script>

app/views/admin/produtos/_list.html.erb
<table class="striped responsive-table">
  <thead>
    <tr>
      <th>Código</th>
      <th>Categoria</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th style="width: 8%;">Ativo</th>
      <th style="width: 8%;">Destaque</th>
      <th>Capa</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody id="item_list">
    <%= render @produtos %>
  </tbody>
</table>

app/views/admin/produtos/_produto.html.erb
<tr>
  <td class="cod">
    <span>
      <%= produto.id %>
    </span>
  </td>
  <td><span class="span purple-text peso-7"><%= I18n.t("categoria.tipos.#{produto.categoria.tipos}") %></span> <%= "#{produto.categoria.nome}" %></td>
  <td><%= "#{produto.nome}" %></td>
  <td><%= produto.descricao %></td>
  <td>
    <%= produto.ativo ? "<i class='material-icons green-text'>check_box</i>".html_safe : "<i class='material-icons red-text'>check_box_outline_blank</i>".html_safe %>
  </td>
  <td>
    <%= produto.destaque ? "<i class='material-icons orange-text'>star</i>".html_safe : "<i class='material-icons orange-text'>star_border</i>".html_safe %>
  </td>
  <td>
    <img src="<%= capa(produto) %>" style="max-height: 2rem;" >
  </td>
  <td class="actions">
    <%= link_to edit_admin_produto_path(produto), class: "btn shadow blue small", title: "Editar #{produto.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>edit</i>
    <% end %>
    <%= link_to admin_produto_path(produto), class: "btn shadow orange small", title: "Visualizar #{produto.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>search</i>
    <% end %>
    <%= link_to admin_produto_path(produto), class: "btn shadow purple small", title: "Rendimento #{produto.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>insert_chart</i>
    <% end %>
    <% if admin %>
      <%= link_to "<i class='material-icons prefix'>delete</i>".html_safe, admin_produto_path(produto), remote: true, method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn shadow red small", title: "Deletar #{produto.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' %>
    <% end %>
  </td>
</tr>

app/views/admin/produtos/create.js.erb
<% if @produto.errors.any? %>
	<% @produto.errors.full_messages.each do |msg| %>
		M.toast({html: '<%= msg %>', classes: 'red'});
	<% end %>
<% end %>

app/views/admin/produtos/edit.html.erb
<%= render "form" %>

app/views/admin/produtos/index.html.erb
<%= link_to "Novo Produto".html_safe, new_admin_produto_path(), class: "btn shadow green" %>
<div class="row layout">
	<div class="input-field col s12 m6 l3">
		<input id="codigo" type="text" class="validate">
		<label class="active" for="codigo">Código</label>
	</div>
	<div class="input-field col s12 m6 l3">
		<input id="nome" type="text" class="validate">
		<label class="active" for="nome">Nome</label>
	</div>
	<div class="input-field col s12 m6 l3">
		<a id="buscar" class="btn shadow black small">Buscar</a>
	</div>
</div>

<div class="row layout claro">
	<div class="col s12 m12 l12">
		<div id="produto_list">
			<%= render "list" %>
		</div>
	</div>
</div>

<script type="text/javascript">
	$("#buscar").click(function(){
		$("#produto_list").removeClass("animated tada");
		var codigo = $("#codigo").val();
		var nome = $("#nome").val();
		$.ajax({
			url: "/admin/produtos",
			method: "get",
			dataType: "script",
			data: {
				'id': 			codigo,
				'nome': 		nome
			}
		});
	});
$("input").keypress(function() {
    if (event.which == 13) $("a#buscar").trigger( "click" )
});
</script>

app/views/admin/produtos/index.js.erb
$("#produto_list").html("<%= j( render 'list'  )%>").addClass("animated tada");

app/views/admin/produtos/new.html.erb
<%= render "form" %>

app/views/admin/produtos/show.html.erb
<div class="">
	<div class="row">
		<% @produto.attributes.each do |key, value| %>
			<div class="col s12 m12 l6">

			      <div class="card white">
			        <div class="card-content black-text" style="min-height: 100px;">
					<strong><%= "#{key}".titleize %>: </strong> <%= (value.class == TrueClass) ? "<i class='material-icons green-text'>check_box</i>".html_safe : (value.class == FalseClass) ? "<i class='material-icons red-text'>close</i>".html_safe : "#{ value}" %>	
			        </div>
			      </div>

			</div>
		<% end %>
	</div>
</div>

app/views/admin/produtos/update.js.erb
<% if @produto.errors.any? %>
	<% @produto.errors.full_messages.each do |msg| %>
		M.toast({html: '<%= msg %>', classes: 'red'});
	<% end %>
<% end %>