config/routes.rb
Rails.application.routes.draw do



  ########################################################################################################
  
  namespace :admin do
    
    controller :users do
    end
    resources :users
    
    controller :categorias do
    end
    resources :categorias
    
    controller :produtos do
    end
    resources :produtos
    
    controller :pages do
      get '/home' => :home
      get '/logs' => :logs
    end

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}
    
    controller :produtos do
    end
    resources :produtos, only: [:show, :index]

  controller :pages do
    get '/home' => :home
  end

  root 'pages#home'
  get '*path' => redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :nome, presence: true


  after_create :log_for_create
  #after_update :log_for_update, if: -> { self.changes }

  def log_for_create
    Log.create(descricao: "Novo usuário criado!", objeto: {"class" => "green", "id" => self.id, "tipo" => "users", "descricao" => self.nome})
  end

  def log_for_update
    Log.create(descricao: "Alteração no usuário #{self.id} - #{self.nome}", objeto: {"id" => self.id, "tipo" => "user", "descricao" => self.nome}) 
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]


	def index
		conditions = []
    conditions << "users.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
    conditions << "users.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?

		@users = User.where(conditions.join(" AND ")).order("created_at desc")
	end

	def show
	end

	def edit
	end

	def update
	end

	def new
		@user = User.new
	end

	def create
	end

	def destroy
	end

	private

	def set_user
		@user = User.find(params[:id].to_i)
	end

end

app/helpers/user_helper.rb
module UserHelper

	def admin user = current_user
		user.admin
	end

end

app/views/admin/users/_list.html.erb
<table class="striped responsive-table">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>CPF</th>
      <th>Admin</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody id="item_list">
    <%= render @users %>
  </tbody>
</table>

app/views/admin/users/_user.html.erb
<tr>
  <td class="cod">
    <span>
      <%= user.id %>
    </span>
  </td>
  <td><%= "#{user.nome}" %></td>
  <td><%= user.cpf %></td>
  <td>
    <%= user.admin ? "<i class='material-icons green-text'>check_box</i>".html_safe : "<i class='material-icons red-text'>check_box_outline_blank</i>".html_safe %></td>
  <td class="actions">
    <%= link_to edit_admin_user_path(user), class: "btn shadow blue small", title: "Editar #{user.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>edit</i>
    <% end %>
    <%= link_to admin_user_path(user), class: "btn shadow orange small", title: "Visualizar #{user.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>search</i>
    <% end %>
    <%= link_to admin_user_path(user), class: "btn shadow purple small", title: "Rendimento #{user.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>insert_chart</i>
    <% end %>
    <% if current_user.admin %>
      <%= link_to "<i class='material-icons prefix'>delete</i>".html_safe, admin_user_path(user), remote: true, method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn shadow red small", title: "Deletar #{user.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' %>
    <% end %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<%= link_to "Novo User".html_safe, new_admin_user_path(), class: "btn shadow green" %>
<div class="row layout">
	<div class="input-field col s12 m6 l3">
		<input id="codigo" type="text" class="validate">
		<label class="active" for="codigo">Código</label>
	</div>
	<div class="input-field col s12 m6 l3">
		<input id="nome" type="text" class="validate">
		<label class="active" for="nome">Nome</label>
	</div>
	<div class="input-field col s12 m6 l3">
		<a id="buscar" class="btn shadow black small">Buscar</a>
	</div>
</div>

<div class="row layout claro">
	<div class="col s12 m12 l12">
		<div id="user_list">
			<%= render "list" %>
		</div>
	</div>
</div>

<script type="text/javascript">
	$("#buscar").click(function(){
		$("#user_list").removeClass("animated tada");
		var codigo = $("#codigo").val();
		var nome = $("#nome").val();
		$.ajax({
			url: "/admin/users",
			method: "get",
			dataType: "script",
			data: {
				'id': 			codigo,
				'nome': 		nome
			}
		});
	});
$("input").keypress(function() {
    if (event.which == 13) $("a#buscar").trigger( "click" )
});
</script>

app/views/admin/users/index.js.erb
$("#user_list").html("<%= j( render 'list'  )%>").addClass("animated tada");