config/routes.rb
Rails.application.routes.draw do



  ########################################################################################################
  
  namespace :admin do
    
    controller :users do
    end
    resources :users
    
    controller :categorias do
    end
    resources :categorias
    
    controller :produtos do
    end
    resources :produtos
    
    controller :pages do
      get '/home' => :home
      get '/logs' => :logs
    end

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}
    
    controller :produtos do
    end
    resources :produtos, only: [:show, :index]

  controller :pages do
    get '/home' => :home
  end

  root 'pages#home'
  get '*path' => redirect('/')
end

app/models/categoria.rb
class Categoria < ApplicationRecord

  enum tipos: [:oculos, :relogios, :tenis]

  validates :nome, :tipos, presence: true
  validates :nome, uniqueness: { scope: :tipos }

  
  has_many :produtos

  after_create :log_for_create
  #after_update :log_for_update, if: -> { self.changes }

  def log_for_create
    Log.create(descricao: "Nova categoria criada!", objeto: {"class" => "green", "id" => self.id, "tipo" => "categorias", "descricao" => "#{self.nome} - #{self.descricao}"})
  end

  def log_for_update
    Log.create(descricao: "Alteração na categoria #{self.id} - #{self.nome}", objeto: {"id" => self.id, "tipo" => "user", "descricao" => "#{self.nome} - #{self.descricao}"}) 
  end

end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < Admin::ApplicationController
    before_action :set_categoria, only: [:show, :edit, :update, :destroy]


	def index
		conditions = []
    conditions << "categorias.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
    conditions << "categorias.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?

		@categorias = Categoria.where(conditions.join(" AND ")).order("created_at desc")

	end

	def show
	end

	def edit
	end

	def update
    respond_to do |format|
        if @categoria.update(categoria_params)
            format.js {render inline: "M.toast({html: 'Atualizado!', classes: 'green'}); " }
        else
            format.js {render inline: "M.toast({html: 'Não foi possível editar a categoria #{@categoria.nome}', classes: 'red'}); " }
        end
    end
	end

	def new
		@categoria = Categoria.new
	end

	def create
		@categoria = Categoria.new(categoria_params)
		if @categoria.save
		    redirect_to edit_admin_categoria_path(@categoria), notice: "Categoria #{@categoria.nome} criado com sucesso!"
		else
	    respond_to do |format|
	        format.js
	    end
		end
	end

	def destroy
	end

	private

  def categoria_params
      params.require(:categoria).permit(:nome, :descricao, :tipos, :ativo)
  end

	def set_categoria
		@categoria = Categoria.find(params[:id].to_i)
	end

end

app/helpers/categoria_helper.rb
module CategoriaHelper


	def categoria_tipos
    Categoria.tipos.map do |r, key|
     [I18n.t("categoria.tipos.#{r}"), r]
    end
	end

	def categorias_relogios
		Categoria.relogios
	end
	
	def categorias_tenis
		Categoria.tenis
	end
	
	def categorias_oculos
		Categoria.oculos
	end



end

app/views/admin/categorias/_categoria.html.erb
<tr>
  <td class="cod">
    <span>
      <%= categoria.id %>
    </span>
  </td>
  <td><%= I18n.t("categoria.tipos.#{categoria.tipos}") %></td>
  <td><%= categoria.nome %></td>
  <td><%= categoria.descricao %></td>
  <td>
    <%= categoria.ativo ? "<i class='material-icons green-text'>check_box</i>".html_safe : "<i class='material-icons red-text'>check_box_outline_blank</i>".html_safe %>
  </td>
  <td>
    <%= link_to edit_admin_categoria_path(categoria), class: "btn shadow blue small", title: "Editar #{categoria.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>edit</i>
    <% end %>
    <%= link_to admin_categoria_path(categoria), class: "btn shadow orange small", title: "Visualizar #{categoria.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>search</i>
    <% end %>
  </td>
</tr>

app/views/admin/categorias/_form.html.erb
<div class="layout">
	<%= form_for [:admin, @categoria], remote: true do |f| %>


  <div class="row">
    <div class="col s12 m12 l8 offset-l2">
      <div class="card">
        <div class="card-content">
			<div class="row">
				<div class="field">
					<div class="input-field col s12 m12 l12">
						<i class="material-icons prefix">description</i>
						<%= f.text_field :nome  %>
						<label for="categoria_nome">Name</label>
					</div>
				</div>

				<div class="field">
					<div class="input-field col s12 m12 l12">
						<i class="material-icons prefix">local_offer</i>
						<%= f.collection_select :tipos, categoria_tipos, :last, :first, { prompt: "Selecionar Tipo" } %>
						<%= f.label :tipos %>
					</div>
				</div>

				<div class="field">
					<div class="input-field col s12 m12 l12">
						<i class="material-icons prefix">description</i>
						<%= f.text_field :descricao %>
						<label for="categoria_descricao">Descrição</label>
					</div>
				</div>


			</div>
			<div class="row">
				<div class="col s12 m12 l12" >
					<label>
						<%= f.check_box :ativo, class: "filled-in checkbox"  %> 
						<span class="">Ativo</span>
					</label>
				</div>
			</div>
			<div class="action">
							<button type="submit" class="send btn shadow green dark small right">Salvar</button>
			</div>
        </div>
      </div>
    </div>
  </div>
	<% end %>

</div>


<script type="text/javascript">
  $(document).ready(function(){
    $('select').formSelect();
  });
</script>

app/views/admin/categorias/_list.html.erb
<table class="striped responsive-table">
  <thead>
    <tr>
      <th>Código</th>
      <th>Tipo</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Ativo</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody id="item_list">
  <%= render @categorias %>
  </tbody>
</table>

app/views/admin/categorias/create.js.erb
<% if @categoria.errors.any? %>
	<% @categoria.errors.full_messages.each do |msg| %>
		M.toast({html: '<%= msg %>', classes: 'red'});
	<% end %>
<% end %>

app/views/admin/categorias/edit.html.erb
<%= render "form" %>

app/views/admin/categorias/index.html.erb
<div class="row">
	<div class="col s12 m12 l2">
		<%= link_to "Adicionar Categoria", new_admin_categoria_path, class: "btn shadow green small" %>
	</div>
</div>
<div class="row layout">
	<div class="input-field col s12 m6 l3">
		<input id="id" type="text" class="validate">
		<label class="active" for="id">Código</label>
	</div>
	<div class="input-field col s12 m6 l3">
		<input id="name" type="text" class="validate">
		<label class="active" for="name">Nome</label>
	</div>
	<div class="input-field col s12 m6 l3">
		<a id="buscar" class="btn shadow black small">Buscar</a>
	</div>
</div>

<div class="row layout claro">
	<div class="col s12 m12 l12">
		<div id="categoria_list">
			<%= render "list" %>
		</div>
	</div>
</div>

app/views/admin/categorias/index.js.erb
$("#categoria_list").html("<%= j( render 'list'  )%>").addClass("animated tada");

app/views/admin/categorias/new.html.erb
<%= render "form" %>

app/views/admin/categorias/show.html.erb
<div class="">
	<div class="row">
		<% @categoria.attributes.each do |key, value| %>
			<div class="col s12 m12 l6">

			      <div class="card white">
			        <div class="card-content black-text" style="min-height: 100px;">
					<strong><%= "#{key}".titleize %>: </strong> <%= (value.class == TrueClass) ? "<i class='material-icons green-text'>check_box</i>".html_safe : (value.class == FalseClass) ? "<i class='material-icons red-text'>close</i>".html_safe : "#{ value}" %>	
			        </div>
			      </div>

			</div>
		<% end %>
	</div>
</div>